version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server
    image: stats_service
    container_name: stats_service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_HOST=stats-db
      - DB_PORT=5432
      - DB_NAME=stat_serv_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat_serv_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


  ewm-service:
    build: ./ewm-service
    image: ewm_service
    container_name: ewm_cont
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - CLIENT_URL=http://stats-server:9090
      - DB_HOST=ewm-db
      - DB_PORT=5432
      - DB_NAME=ewm_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm_postgres
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_service_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
