version: '3.1'
services:
  stats-server:
    build: ./stats-service/stats-server   # указание на модуль сервера (?)
    image: stats_service_image
    container_name: stats_service_cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=stats-db
      - DB_PORT=5432
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stat_db

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


#  ewm-service:
#    build: ./ewm-service
#    image: ewm_service
#    container_name: ewm_cont
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - DB_NAME=main
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot

#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm_postgres
#    ports:
#      - "xxxx:xxxx"
#    environment:
#      - POSTGRES_DB=main
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot
