version: '3.1'
services:
  stats-server:
    build: ./stats-service
    image: stats_service
    container_name: stats_cont
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - DB_NAME=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot
      - DB_HOST=db
      - DB_PORT=5432

  stats-db:
    image: postgres:14-alpine
    container_name: stats_postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot


#  ewm-service:
#    build: ./ewm-service
#    image: ewm_service
#    container_name: ewm_cont
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#    environment:
#      - DB_NAME=main
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot
#      - DB_HOST=
#      - DB_PORT=

#  ewm-db:
#    image: postgres:14-alpine
#    container_name: ewm_postgres
#    ports:
#      - "xxxx:xxxx"
#    environment:
#      - POSTGRES_DB=main
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=iamroot
